TEAMS:
CREATE OR REPLACE TABLE teams_combined as
            SELECT DISTINCT
            
	log_table.SEASON_ID,
	COALESCE(log_table.TEAM_ID,teams_advanced.TEAM_ID,teams_fourfactors.TEAM_ID,teams_misc.TEAM_ID,teams_scoring.TEAM_ID,teams_traditional.TEAM_ID) as TEAM_ID,
	COALESCE(log_table.TEAM_ABBREVIATION,lines_table.TEAM_ABBREVIATION,teams_advanced.TEAM_ABBREVIATION,teams_fourfactors.TEAM_ABBREVIATION,teams_misc.TEAM_ABBREVIATION,teams_scoring.TEAM_ABBREVIATION,teams_traditional.TEAM_ABBREVIATION) as TEAM_ABBREVIATION,
	COALESCE(log_table.TEAM_NAME,teams_advanced.TEAM_NAME,teams_fourfactors.TEAM_NAME,teams_misc.TEAM_NAME,teams_scoring.TEAM_NAME,teams_traditional.TEAM_NAME) as TEAM_NAME,
	COALESCE(CAST(log_table.GAME_ID AS VARCHAR),CAST(lines_table.GAME_ID AS VARCHAR),CAST(teams_advanced.GAME_ID AS VARCHAR),CAST(teams_fourfactors.GAME_ID AS VARCHAR),CAST(teams_misc.GAME_ID AS VARCHAR),CAST(teams_scoring.GAME_ID AS VARCHAR),CAST(teams_traditional.GAME_ID AS VARCHAR)) as GAME_ID,
	COALESCE(log_table.GAME_DATE,lines_table.GAME_DATE) as GAME_DATE,
	log_table.MATCHUP,
	log_table.WL,
	COALESCE(CAST(log_table.MIN AS VARCHAR),CAST(teams_advanced.MIN AS VARCHAR),CAST(teams_fourfactors.MIN AS VARCHAR),CAST(teams_misc.MIN AS VARCHAR),CAST(teams_scoring.MIN AS VARCHAR),CAST(teams_traditional.MIN AS VARCHAR)) as MIN,
	COALESCE(log_table.PTS,teams_traditional.PTS) as PTS,
	COALESCE(log_table.FGM,teams_traditional.FGM) as FGM,
	COALESCE(log_table.FGA,teams_traditional.FGA) as FGA,
	COALESCE(log_table.FG_PCT,teams_traditional.FG_PCT) as FG_PCT,
	COALESCE(log_table.FG3M,teams_traditional.FG3M) as FG3M,
	COALESCE(log_table.FG3A,teams_traditional.FG3A) as FG3A,
	COALESCE(log_table.FG3_PCT,teams_traditional.FG3_PCT) as FG3_PCT,
	COALESCE(log_table.FTM,teams_traditional.FTM) as FTM,
	COALESCE(log_table.FTA,teams_traditional.FTA) as FTA,
	COALESCE(log_table.FT_PCT,teams_traditional.FT_PCT) as FT_PCT,
	COALESCE(log_table.OREB,teams_traditional.OREB) as OREB,
	COALESCE(log_table.DREB,teams_traditional.DREB) as DREB,
	COALESCE(log_table.REB,teams_traditional.REB) as REB,
	COALESCE(log_table.AST,teams_traditional.AST) as AST,
	COALESCE(log_table.STL,teams_traditional.STL) as STL,
	COALESCE(log_table.BLK,teams_misc.BLK,teams_traditional.BLK) as BLK,
	log_table.TOV,
	COALESCE(log_table.PF,teams_misc.PF,teams_traditional.PF) as PF,
	COALESCE(log_table.PLUS_MINUS,teams_traditional.PLUS_MINUS) as PLUS_MINUS,
	lines_table.LINE,
	lines_table.OU,
	COALESCE(teams_advanced.TEAM_CITY,teams_fourfactors.TEAM_CITY,teams_misc.TEAM_CITY,teams_scoring.TEAM_CITY,teams_traditional.TEAM_CITY) as TEAM_CITY,
	teams_advanced.E_OFF_RATING,
	teams_advanced.OFF_RATING,
	teams_advanced.E_DEF_RATING,
	teams_advanced.DEF_RATING,
	teams_advanced.E_NET_RATING,
	teams_advanced.NET_RATING,
	teams_advanced.AST_PCT,
	teams_advanced.AST_TOV,
	teams_advanced.AST_RATIO,
	COALESCE(teams_advanced.OREB_PCT,teams_fourfactors.OREB_PCT) as OREB_PCT,
	teams_advanced.DREB_PCT,
	teams_advanced.REB_PCT,
	teams_advanced.E_TM_TOV_PCT,
	COALESCE(teams_advanced.TM_TOV_PCT,teams_fourfactors.TM_TOV_PCT) as TM_TOV_PCT,
	COALESCE(teams_advanced.EFG_PCT,teams_fourfactors.EFG_PCT) as EFG_PCT,
	teams_advanced.TS_PCT,
	teams_advanced.USG_PCT,
	teams_advanced.E_USG_PCT,
	teams_advanced.E_PACE,
	teams_advanced.PACE,
	teams_advanced.PACE_PER40,
	teams_advanced.POSS,
	teams_advanced.PIE,
	teams_fourfactors.FTA_RATE,
	teams_fourfactors.OPP_EFG_PCT,
	teams_fourfactors.OPP_FTA_RATE,
	teams_fourfactors.OPP_TOV_PCT,
	teams_fourfactors.OPP_OREB_PCT,
	teams_misc.PTS_OFF_TOV,
	teams_misc.PTS_2ND_CHANCE,
	teams_misc.PTS_FB,
	teams_misc.PTS_PAINT,
	teams_misc.OPP_PTS_OFF_TOV,
	teams_misc.OPP_PTS_2ND_CHANCE,
	teams_misc.OPP_PTS_FB,
	teams_misc.OPP_PTS_PAINT,
	teams_misc.BLKA,
	teams_misc.PFD,
	teams_scoring.PCT_FGA_2PT,
	teams_scoring.PCT_FGA_3PT,
	teams_scoring.PCT_PTS_2PT,
	teams_scoring.PCT_PTS_2PT_MR,
	teams_scoring.PCT_PTS_3PT,
	teams_scoring.PCT_PTS_FB,
	teams_scoring.PCT_PTS_FT,
	teams_scoring.PCT_PTS_OFF_TOV,
	teams_scoring.PCT_PTS_PAINT,
	teams_scoring.PCT_AST_2PM,
	teams_scoring.PCT_UAST_2PM,
	teams_scoring.PCT_AST_3PM,
	teams_scoring.PCT_UAST_3PM,
	teams_scoring.PCT_AST_FGM,
	teams_scoring.PCT_UAST_FGM,
	teams_traditional.TO,
        FROM log_table
left join teams_traditional on log_table.GAME_ID::int = teams_traditional.GAME_ID::int and log_table.TEAM_ABBREVIATION = teams_traditional.TEAM_ABBREVIATION
left join teams_scoring on log_table.GAME_ID::int = teams_scoring.GAME_ID::int and log_table.TEAM_ABBREVIATION = teams_scoring.TEAM_ABBREVIATION
left join teams_misc on log_table.GAME_ID::int = teams_misc.GAME_ID::int and log_table.TEAM_ABBREVIATION = teams_misc.TEAM_ABBREVIATION
left join teams_advanced on log_table.GAME_ID::int = teams_advanced.GAME_ID::int and log_table.TEAM_ABBREVIATION = teams_advanced.TEAM_ABBREVIATION
left join lines_table on log_table.GAME_ID::int = lines_table.GAME_ID::int and log_table.TEAM_ABBREVIATION = lines_table.TEAM_ABBREVIATION
left join teams_fourfactors on log_table.GAME_ID::int = teams_fourfactors.GAME_ID::int and log_table.TEAM_ABBREVIATION = teams_fourfactors.TEAM_ABBREVIATION

PLAYERS:
CREATE OR REPLACE TABLE players_combined as
            SELECT DISTINCT
            
	log_table.SEASON_ID,
	log_table.TEAM_ID,
	log_table.TEAM_ABBREVIATION,
	log_table.TEAM_NAME,
	log_table.GAME_ID,
	log_table.GAME_DATE,
	log_table.MATCHUP,
	log_table.WL,
	COALESCE(players_fourfactors.MIN,players_advanced.MIN,players_misc.MIN,players_scoring.MIN,players_traditional.MIN) as MIN,
	players_traditional.PTS,
	players_traditional.FGM,
	players_traditional.FGA,
	players_traditional.FG_PCT,
	players_traditional.FG3M,
	players_traditional.FG3A,
	players_traditional.FG3_PCT,
	players_traditional.FTM,
	players_traditional.FTA,
	players_traditional.FT_PCT,
	players_traditional.OREB,
	players_traditional.DREB,
	players_traditional.REB,
	players_traditional.AST,
	players_traditional.STL,
	COALESCE(players_misc.BLK,players_traditional.BLK) as BLK,
	COALESCE(players_misc.PF,players_traditional.PF) as PF,
	players_traditional.PLUS_MINUS,
	COALESCE(players_fourfactors.TEAM_CITY,players_advanced.TEAM_CITY,players_misc.TEAM_CITY,players_scoring.TEAM_CITY,players_traditional.TEAM_CITY) as TEAM_CITY,
	COALESCE(players_fourfactors.PLAYER_ID,players_advanced.PLAYER_ID,players_misc.PLAYER_ID,players_scoring.PLAYER_ID,players_traditional.PLAYER_ID) as PLAYER_ID,
	COALESCE(players_fourfactors.PLAYER_NAME,players_advanced.PLAYER_NAME,players_misc.PLAYER_NAME,players_scoring.PLAYER_NAME,players_traditional.PLAYER_NAME) as PLAYER_NAME,
	COALESCE(players_fourfactors.NICKNAME,players_advanced.NICKNAME,players_misc.NICKNAME,players_scoring.NICKNAME,players_traditional.NICKNAME) as NICKNAME,
	COALESCE(players_fourfactors.START_POSITION,players_advanced.START_POSITION,players_misc.START_POSITION,players_scoring.START_POSITION,players_traditional.START_POSITION) as START_POSITION,
	COALESCE(players_fourfactors.COMMENT,players_advanced.COMMENT,players_misc.COMMENT,players_scoring.COMMENT,players_traditional.COMMENT) as COMMENT,
	players_advanced.E_OFF_RATING,
	players_advanced.OFF_RATING,
	players_advanced.E_DEF_RATING,
	players_advanced.DEF_RATING,
	players_advanced.E_NET_RATING,
	players_advanced.NET_RATING,
	players_advanced.AST_PCT,
	players_advanced.AST_TOV,
	players_advanced.AST_RATIO,
	COALESCE(players_fourfactors.OREB_PCT,players_advanced.OREB_PCT) as OREB_PCT,
	players_advanced.DREB_PCT,
	players_advanced.REB_PCT,
	COALESCE(players_fourfactors.TM_TOV_PCT,players_advanced.TM_TOV_PCT) as TM_TOV_PCT,
	COALESCE(players_fourfactors.EFG_PCT,players_advanced.EFG_PCT) as EFG_PCT,
	players_advanced.TS_PCT,
	players_advanced.USG_PCT,
	players_advanced.E_USG_PCT,
	players_advanced.E_PACE,
	players_advanced.PACE,
	players_advanced.PACE_PER40,
	players_advanced.POSS,
	players_advanced.PIE,
	players_fourfactors.FTA_RATE,
	players_fourfactors.OPP_EFG_PCT,
	players_fourfactors.OPP_FTA_RATE,
	players_fourfactors.OPP_TOV_PCT,
	players_fourfactors.OPP_OREB_PCT,
	players_misc.PTS_OFF_TOV,
	players_misc.PTS_2ND_CHANCE,
	players_misc.PTS_FB,
	players_misc.PTS_PAINT,
	players_misc.OPP_PTS_OFF_TOV,
	players_misc.OPP_PTS_2ND_CHANCE,
	players_misc.OPP_PTS_FB,
	players_misc.OPP_PTS_PAINT,
	players_misc.BLKA,
	players_misc.PFD,
	players_scoring.PCT_FGA_2PT,
	players_scoring.PCT_FGA_3PT,
	players_scoring.PCT_PTS_2PT,
	players_scoring.PCT_PTS_2PT_MR,
	players_scoring.PCT_PTS_3PT,
	players_scoring.PCT_PTS_FB,
	players_scoring.PCT_PTS_FT,
	players_scoring.PCT_PTS_OFF_TOV,
	players_scoring.PCT_PTS_PAINT,
	players_scoring.PCT_AST_2PM,
	players_scoring.PCT_UAST_2PM,
	players_scoring.PCT_AST_3PM,
	players_scoring.PCT_UAST_3PM,
	players_scoring.PCT_AST_FGM,
	players_scoring.PCT_UAST_FGM,
	players_traditional.TO,
        FROM log_table
left join players_advanced on log_table.GAME_ID::int = players_advanced.GAME_ID::int and log_table.TEAM_ABBREVIATION = players_advanced.TEAM_ABBREVIATION
left join players_fourfactors on players_advanced.GAME_ID::int = players_fourfactors.GAME_ID::int and players_advanced.PLAYER_NAME = players_fourfactors.PLAYER_NAME
left join players_traditional on players_fourfactors.GAME_ID::int = players_traditional.GAME_ID::int and players_fourfactors.PLAYER_NAME = players_traditional.PLAYER_NAME
left join players_misc on players_traditional.GAME_ID::int = players_misc.GAME_ID::int and players_traditional.PLAYER_NAME = players_misc.PLAYER_NAME
left join players_scoring on players_misc.GAME_ID::int = players_scoring.GAME_ID::int and players_misc.PLAYER_NAME = players_scoring.PLAYER_NAME

